### ISSUE TITLE
Sanity desks opens up broken

### ISSUE THREAD

**Issue by sachinsancheti1** [HeySugar/sanity-template-gatsby-hey-sugar#3]
![broken-desk](https://user-images.githubusercontent.com/6279770/114482814-d9194600-9c24-11eb-804d-a8055a08fdfa.jpg)

Found this when logging in the first go.

**Comment by sachinsancheti1** [comment]
Opened PR https://github.com/HeySugar/sanity-template-gatsby-hey-sugar/pull/4

**Comment by JamieBradders** [comment]
Thanks @sachinsancheti1 I've merged this and will now close the issue 👍

Resolved as per #4

**Comment by sachinsancheti1** [comment]
You're welcome. Happy to contribute to make this a fully functional application.
